[build]
  functions = "functions"  # Asegúrate de que este directorio existe y contiene tus funciones

[[redirects]]
  from = "/api/*"               # Cambia esto según cómo quieras acceder a tu API
  to = "/.netlify/functions/app"  # Cambia "app" al nombre del archivo de función que crees
  status = 200
